// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package backend

import (
	Init2 "awesomeProject4/backend/Init"
	"awesomeProject4/backend/api/handler"
	"awesomeProject4/backend/api/server"
	"awesomeProject4/backend/event"
	"awesomeProject4/backend/repository"
	"awesomeProject4/backend/repository/dao"
	"awesomeProject4/backend/service"

	"github.com/IBM/sarama"
	"github.com/gin-gonic/gin"
)

func InitializeServer() (*gin.Engine, sarama.ConsumerGroup, *event.InterviewEvaluationConsumer, error) {
	log := Init2.InitLogger()
	db, err := Init2.InitMysql()
	if err != nil {
		return nil, nil, nil, err
	}
	cmdable := Init2.InitRedis()
	client := Init2.NewKafka()
	syncProducer := Init2.NewKafkaProducer(client)
	consumerGroup := Init2.NewConsumer("interview-evaluation-consumer", client)
	userDAO := dao.NewUserDAO(db)
	userModelDAO := dao.NewUserModelDAO(db)
	resumeDAO := dao.NewResumeDAO(db)
	interviewRecordDAO := dao.NewInterviewRecordDAO(db)
	interviewDialogueDAO := dao.NewInterviewDialogueDAO(db)
	interviewEvaluationDAO := dao.NewInterviewEvaluationDAO(db)
	evaluationDetailDAO := dao.NewEvaluationDetailDAO(db)
	predictionDAO := dao.NewPredictionDAO(db)
	userRepository := repository.NewUserRepository(userDAO)
	userModelRepository := repository.NewUserModelRepository(userModelDAO)
	resumeRepository := repository.NewResumeRepository(resumeDAO, cmdable)
	interviewRecordRepository := repository.NewInterviewRecordRepository(interviewRecordDAO)
	interviewDialogueRepository := repository.NewInterviewDialogueRepository(interviewDialogueDAO)
	interviewEvaluationRepository := repository.NewInterviewEvaluationRepository(interviewEvaluationDAO)
	evaluationDetailRepository := repository.NewEvaluationDetailRepository(evaluationDetailDAO)
	predictionRepository := repository.NewPredictionRepository(predictionDAO)
	userService := service.NewUserService(userRepository)
	userModelService := service.NewUserModelService(userModelRepository)
	resumeService := service.NewResumeService(resumeRepository)
	interviewRecordService := service.NewInterviewRecordService(interviewRecordRepository)
	interviewDialogueService := service.NewInterviewDialogueService(interviewDialogueRepository)
	interviewEvaluationService := service.NewInterviewEvaluationService(interviewEvaluationRepository)
	evaluationDetailService := service.NewEvaluationDetailService(evaluationDetailRepository)
	predictionService := service.NewPredictionService(predictionRepository)
	_ = interviewEvaluationService
	interviewEvaluationProducer := event.NewInterviewEvaluationProducer(syncProducer)
	interviewEvaluationConsumer := event.NewInterviewEvaluationConsumer(interviewDialogueService, evaluationDetailService, predictionService)
	handler := handler.NewHandler(log, userService, userModelService, interviewDialogueService, evaluationDetailService, predictionService, interviewEvaluationProducer, resumeService, interviewRecordService, interviewDialogueDAO, cmdable)
	engine := server.NewGinEngine(handler)
	return engine, consumerGroup, interviewEvaluationConsumer, nil
}
